### ISSUE TITLE
Does the .NET Core SDK 3.1.300 really solves the untracked files issue?

### ISSUE THREAD

**Issue by 0xced** [clairernovotny/DeterministicBuilds#4]
I already asked this question on https://github.com/dotnet/sdk/issues/10614#issuecomment-634029130 but did not get a response yet, so I'm trying here since it looks like a good place with Claire being very knowledgeable about deterministic builds.

Let's describe the problem with a concrete example. Here's how I'm packing https://github.com/0xced/DockerRunner, commit d6d8917e7f208dbaacd9dd6ff25a439031d5dfd1 (current master branch as of writing):

```bash
dotnet --version
3.1.300
dotnet pack -c Release /p:ContinuousIntegrationBuild=true
  Successfully created package '[...]DockerRunner\src\bin\Release\DockerRunner.0.9.0-alpha.0.21.nupkg'.
```

When I open the resulting `DockerRunner.0.9.0-alpha.0.21.nupkg` in NuGet Package Explorer, *Source Link* and *Deterministic* health items have a warning sign with this tooltip:

> Contains untracked sources:
> To Fix:
> `<EmbedUntrackedSources>true</EmbedUntrackedSources>`
> 
> Also, use 3.1.300 SDK to build or
workaround in: https://github.com/dotnet/sourcelink/issues/572
Assembly: lib\netstandard2.0\DockerRunner.dll
> `/_/src/obj/Release/netstandard2.0/.NETStandard,Version=v2.0.AssemblyAttributes.cs`
>  `/_/src/obj/Release/netstandard2.0/DockerRunner.AssemblyInfo.cs`

Now, let's add the workaround described on https://github.com/dotnet/sourcelink/issues/572 in `DockerRunner.csproj`:

```xml
<PropertyGroup>
  <TargetFrameworkMonikerAssemblyAttributesPath>$([System.IO.Path]::Combine('$(IntermediateOutputPath)','$(TargetFrameworkMoniker).AssemblyAttributes$(DefaultLanguageSourceExtension)'))</TargetFrameworkMonikerAssemblyAttributesPath>
</PropertyGroup>
<ItemGroup>
  <EmbeddedFiles Include="$(GeneratedAssemblyInfoFile)" />
</ItemGroup>
```

Then I try to pack again with `dotnet pack -c Release /p:ContinuousIntegrationBuild=true` and with this workaround, NuGet Package Explorer reports that *Source Link* and *Determinisc* are valid with a checkmark icon.

To me, it seems that the .NET Core SDK 3.1.300 does not actually solve the untracked sources issue. Am I missing something? (Note that I have `<EmbedUntrackedSources>` set to `true` in the csproj)

**Comment by clairernovotny** [comment]
@tmat?

**Comment by tmat** [comment]
Fix for TargetFrameworkMonikerAssemblyAttributesPath is in msbuild 16.6: https://github.com/microsoft/msbuild/pull/5101. 
Fix for `<EmbeddedFiles Include="$(GeneratedAssemblyInfoFile)" />` is in should be in 3.1.3xx: https://github.com/dotnet/sdk/pull/10616.

**Comment by 0xced** [comment]
I finally figured out why the *AssemblyAttributes* and *AssemblyInfo* files were not embedded in the pdb by SourceLink even when using the .NET Core SDK 3.1.300 and setting `EmbedUntrackedSources` to `true`.

### The git repository was missing a `.gitignore` file.

I have a global .gitignore file with common git ignore patterns such as `bin`, `obj`, `node_modules` etc. but the repository did not have its own `.gitignore` file. After adding it, SourceLink works as expected and NuGet Package Explorer reports that the package health is ✅.

<hr>

For the record, I built [SourceLink](https://github.com/dotnet/sourcelink/) from source code and integrated it in my project by removing `<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />` and adding those 6 imports instead (at the top of the my csproj file):

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="C:\Projects\GitHub\sourcelink\src\Microsoft.Build.Tasks.Git\build\Microsoft.Build.Tasks.Git.props" />
  <Import Project="C:\Projects\GitHub\sourcelink\src\Microsoft.Build.Tasks.Git\build\Microsoft.Build.Tasks.Git.targets" />
  <Import Project="C:\Projects\GitHub\sourcelink\src\SourceLink.Common\build\Microsoft.SourceLink.Common.props" />
  <Import Project="C:\Projects\GitHub\sourcelink\src\SourceLink.Common\build\Microsoft.SourceLink.Common.targets" />
  <Import Project="C:\Projects\GitHub\sourcelink\src\SourceLink.GitHub\build\Microsoft.SourceLink.GitHub.props" />
  <Import Project="C:\Projects\GitHub\sourcelink\src\SourceLink.GitHub\build\Microsoft.SourceLink.GitHub.targets" />

  <PropertyGroup>
```

I also had to modify the following file in the SourceLink repository:
```diff
diff --git a/src/Microsoft.Build.Tasks.Git/build/Microsoft.Build.Tasks.Git.props b/src/Microsoft.Build.Tasks.Git/build/Microsoft.Build.Tasks.Git.props
index 2078031..12be647 100644
--- a/src/Microsoft.Build.Tasks.Git/build/Microsoft.Build.Tasks.Git.props
+++ b/src/Microsoft.Build.Tasks.Git/build/Microsoft.Build.Tasks.Git.props
@@ -1,7 +1,7 @@
 <?xml version="1.0" encoding="utf-8"?>
 <Project>
   <PropertyGroup>
-    <MicrosoftBuildTasksGitAssemblyFile Condition="'$(MSBuildRuntimeType)' != 'Core'">$(MSBuildThisFileDirectory)..\tools\net461\Microsoft.Build.Tasks.Git.dll</MicrosoftBuildTasksGitAssemblyFile>
-    <MicrosoftBuildTasksGitAssemblyFile Condition="'$(MSBuildRuntimeType)' == 'Core'">$(MSBuildThisFileDirectory)..\tools\netcoreapp2.0\Microsoft.Build.Tasks.Git.dll</MicrosoftBuildTasksGitAssemblyFile>
+    <MicrosoftBuildTasksGitAssemblyFile Condition="'$(MSBuildRuntimeType)' != 'Core'">C:\Projects\GitHub\sourcelink\artifacts\bin\Microsoft.Build.Tasks.Git\Debug\net461\Microsoft.Build.Tasks.Git.dll</MicrosoftBuildTasksGitAssemblyFile>
+    <MicrosoftBuildTasksGitAssemblyFile Condition="'$(MSBuildRuntimeType)' == 'Core'">C:\Projects\GitHub\sourcelink\artifacts\bin\Microsoft.Build.Tasks.Git\Debug\netcoreapp2.0\Microsoft.Build.Tasks.Git.dll</MicrosoftBuildTasksGitAssemblyFile>
   </PropertyGroup>
 </Project>
diff --git a/src/SourceLink.Common/build/Microsoft.SourceLink.Common.props b/src/SourceLink.Common/build/Microsoft.SourceLink.Common.props
index 1e2e1f2..1a2b041 100644
--- a/src/SourceLink.Common/build/Microsoft.SourceLink.Common.props
+++ b/src/SourceLink.Common/build/Microsoft.SourceLink.Common.props
@@ -1,8 +1,8 @@
 <?xml version="1.0" encoding="utf-8"?>
 <Project>
   <PropertyGroup>
-    <_MicrosoftSourceLinkCommonAssemblyFile Condition="'$(MSBuildRuntimeType)' != 'Core'">$(MSBuildThisFileDirectory)..\tools\net461\Microsoft.SourceLink.Common.dll</_MicrosoftSourceLinkCommonAssemblyFile>
-    <_MicrosoftSourceLinkCommonAssemblyFile Condition="'$(MSBuildRuntimeType)' == 'Core'">$(MSBuildThisFileDirectory)..\tools\netcoreapp2.0\Microsoft.SourceLink.Common.dll</_MicrosoftSourceLinkCommonAssemblyFile>
+    <_MicrosoftSourceLinkCommonAssemblyFile Condition="'$(MSBuildRuntimeType)' != 'Core'">C:\Projects\GitHub\sourcelink\artifacts\bin\Microsoft.SourceLink.Common\Debug\net461\Microsoft.SourceLink.Common.dll</_MicrosoftSourceLinkCommonAssemblyFile>
+    <_MicrosoftSourceLinkCommonAssemblyFile Condition="'$(MSBuildRuntimeType)' == 'Core'">C:\Projects\GitHub\sourcelink\artifacts\bin\Microsoft.SourceLink.Common\Debug\netcoreapp2.0\Microsoft.SourceLink.Common.dll</_MicrosoftSourceLinkCommonAssemblyFile>
   </PropertyGroup>
 
   <PropertyGroup>
diff --git a/src/SourceLink.GitHub/build/Microsoft.SourceLink.GitHub.targets b/src/SourceLink.GitHub/build/Microsoft.SourceLink.GitHub.targets
index f0a0c1d..9cd038a 100644
--- a/src/SourceLink.GitHub/build/Microsoft.SourceLink.GitHub.targets
+++ b/src/SourceLink.GitHub/build/Microsoft.SourceLink.GitHub.targets
@@ -1,8 +1,8 @@
 <?xml version="1.0" encoding="utf-8"?>
 <Project>
   <PropertyGroup>
-    <_SourceLinkGitHubAssemblyFile Condition="'$(MSBuildRuntimeType)' != 'Core'">$(MSBuildThisFileDirectory)..\tools\net461\Microsoft.SourceLink.GitHub.dll</_SourceLinkGitHubAssemblyFile>
-    <_SourceLinkGitHubAssemblyFile Condition="'$(MSBuildRuntimeType)' == 'Core'">$(MSBuildThisFileDirectory)..\tools\netcoreapp2.0\Microsoft.SourceLink.GitHub.dll</_SourceLinkGitHubAssemblyFile>
+    <_SourceLinkGitHubAssemblyFile Condition="'$(MSBuildRuntimeType)' != 'Core'">C:\Projects\GitHub\sourcelink\artifacts\bin\Microsoft.SourceLink.GitHub\Debug\net461\Microsoft.SourceLink.GitHub.dll</_SourceLinkGitHubAssemblyFile>
+    <_SourceLinkGitHubAssemblyFile Condition="'$(MSBuildRuntimeType)' == 'Core'">C:\Projects\GitHub\sourcelink\artifacts\bin\Microsoft.SourceLink.GitHub\Debug\netcoreapp2.0\Microsoft.SourceLink.GitHub.dll</_SourceLinkGitHubAssemblyFile>
   </PropertyGroup>
 
   <UsingTask TaskName="Microsoft.SourceLink.GitHub.GetSourceLinkUrl" AssemblyFile="$(_SourceLinkGitHubAssemblyFile)"/>
```

Finally, I was able to debug the [GetUntrackedFiles](https://github.com/dotnet/sourcelink/blob/release/1.0.0/src/Microsoft.Build.Tasks.Git/GetUntrackedFiles.cs#L26-L30) MSBuild task step by step with the debugger by inserting `System.Diagnostics.Debugger.Launch();` in its `Execute` method. I had the intuition that the root of the problem was there after looking at the `SetEmbeddedFilesFromSourceControlManagerUntrackedFiles` target with [MSBuild Structured Log Viewer](https://msbuildlog.com). Once I was deep down a method named `IsIgnoredRecursive(string normalizedPosixPath, bool isDirectoryPath)`, I realized that SourceLink did not consider the files in the `obj` directory as untracked files because I had no `.gitignore` file.

**Comment by JimBobSquarePants** [comment]
Maybe I'm doing something wrong here but it looks like I have all the criteria for a successful result but am still getting the warning. 

I have:
-  A `.gitignore` file in the [repository](https://github.com/SixLabors/ImageSharp/blob/138c75b217b27a666d5f26c21bf15fd77a4d84d6/.gitignore#L54)
- `EmbedUntrackedSources` is [true](https://github.com/SixLabors/SharedInfrastructure/blob/bc88dab1746d34048d938566a313848a7a911869/msbuild/props/SixLabors.Src.props#L12-L15) since [CI is always true](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables)
- Am building using SDK Version: [5.0.103](https://github.com/SixLabors/ImageSharp/runs/1922265544?check_suite_focus=true#step:5:9)

Yet I'm still seeing this issue. 

![image](https://user-images.githubusercontent.com/385879/108276945-7c436700-7170-11eb-85e6-40831ecc8f3d.png)

**Comment by tmat** [comment]
@JimBobSquarePants 
Looking into the PDB using [mdv]() tool I can see 3 files that are not in the repo, but only two of them have embedded sources for some reason. The `ImageSharp.InternalsVisibleTo.cs` isn't embedded.

```
2ef: '/_/artifacts/obj/src/ImageSharp/Release/netcoreapp3.1/.NETCoreApp,Version=v3.1.AssemblyAttributes.cs'
2f0: '/_/artifacts/obj/src/ImageSharp/Release/netcoreapp3.1/ImageSharp.AssemblyInfo.cs' 
2f1: '/_/artifacts/obj/src/ImageSharp/Release/netcoreapp3.1/ImageSharp.InternalsVisibleTo.cs'
```

```
 7: 0x300002ef (Document)       Embedded Source
 8: 0x300002f0 (Document)       Embedded Source
```

**Comment by JimBobSquarePants** [comment]
Thanks @tmat for having a look. I wonder whether that has something to do with our custom `GenerateInternalsVisibleTo` target?

https://github.com/SixLabors/SharedInfrastructure/blob/bc88dab1746d34048d938566a313848a7a911869/msbuild/targets/SixLabors.Global.targets#L28-L54

**Comment by tmat** [comment]
Seems like the target is missing dependency:

Needs to be `BeforeTargets="BeforeCompile;CoreCompile"`.

BTW, the .NET 5 SDK has built-in support for generating InternalsVisibleTo (see https://github.com/dotnet/sdk/pull/3439).

**Comment by JimBobSquarePants** [comment]
Thanks! That’s awesome, I’ll give that a go! 

I know about the NET 5 SDK but we don’t target that framework and run individual test runs for various target frameworks.

**Comment by JimBobSquarePants** [comment]
Ah... Turns out that change broke it completely.

![image](https://user-images.githubusercontent.com/385879/108384311-8c0b8b80-7202-11eb-92af-e378afd6ef42.png)

**Comment by clairernovotny** [comment]
How are the symbols being generated? The other two options are dependent on symbols so that's the key here.

**Comment by JimBobSquarePants** [comment]
It's a `snupkg`. 

 I just did some local testing and it appears using the old workaround seems to fix things.
 
 ```xml
  <!--Workaround for Deterministic Builds to ensure custom "InternalsVisibleTo" is included-->
  <PropertyGroup Condition="'$(CI)' == 'true'">
    <TargetFrameworkMonikerAssemblyAttributesPath>$([System.IO.Path]::Combine('$(IntermediateOutputPath)','$(TargetFrameworkMoniker).AssemblyAttributes$(DefaultLanguageSourceExtension)'))</TargetFrameworkMonikerAssemblyAttributesPath>
  </PropertyGroup>
  <ItemGroup Condition="'$(CI)' == 'true'">
    <EmbeddedFiles Include="$(GeneratedAssemblyInfoFile)"/>
  </ItemGroup>
```

![image](https://user-images.githubusercontent.com/385879/108389497-a300ac80-7207-11eb-9492-0932cf6d4d08.png)

My setup is such an edge case it's not worth considering I don't think. I look forward to the days when I can target a minimum of .NET 6 and use the built in tooling.

**Comment by JimBobSquarePants** [comment]
Turns out I'm an idiot and when I downloaded the `nupkg` to check after @tmat fix I didn't download the `snupkg`. Sorry for the time wasted reading the previous messages..

**Comment by clairernovotny** [comment]
No worries, glad it works as expected!

**Comment by higher-order-programmer** [comment]
@0xced thank you very much for sharing that, guy.
