### ISSUE TITLE
Visual Studio warning when Microsoft.SourceLink.GitHub in Directory.build.props

### ISSUE THREAD

**Issue by f2calv** [clairernovotny/DeterministicBuilds#5]
Thanks for this repo, very handy.

I like the idea of putting the Microsoft.SourceLink.GitHub PackageReference in one central place (the Directory.Build.props) however Visual Studio IDE then shows an ugly warning.

![image](https://user-images.githubusercontent.com/16097639/99140840-8cb1e600-2645-11eb-86b7-14054454d33f.png)

I'm running VS 16.9.0 Preview 1.0, any idea how to get rid of the warning... or is this just affecting me?

**Comment by clairernovotny** [comment]
What does the warning say? (Hover over it?) anything in the build/restore output?

**Comment by f2calv** [comment]
Today is a new day and the problem has happily disappeared (I swear I did solution clean and restarted VS...) thanks
